development:
  adapter: postgresql
  encoding: unicode
  database: planet_rater_development
  pool: 5
  username:
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: planet_rater_test
  pool: 5
  username:
  password:
